config/routes.rb
Rails.application.routes.draw do
  
  #共通
  root to:'public/homes#top'
  get 'about' => 'public/homes#about'

  #会員用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#following', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'customers/:id/check' => "customers#check", as: 'check'
    patch 'customers/:id/withdrawal' => "customers#withdrawal", as: 'withdrawal'

    resources :books
    get 'books/search', to: "books#search"
    
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    
    get 'tagsearches/search', to: 'tagsearches#search'
    
    get 'ranks' => 'ranks#rank', as: "rank"

  end

  #管理者用
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :destroy]
  end

  # ゲストログイン
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @reviews = Review.page(params[:page]).per(5)
  end

  def show
    @review = Review.find(params[:id])
  end
  
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = "レビューを削除しました。"
    redirect_to admin_reviews_path
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center my-4">
    <div class="col-md-9 col-lg-8 col-xl-8">
      <div class="px-1 ml-md-2">
        <h5 class="bg-light text-center font-weight-bold ml-5 mb-4" style="width: 130px;">レビュー一覧</h5>
      </div>
      <div class="mx-auto col-12 col-md-10">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr class="text-center">
                <th class="bg-light">タイトル</th>
                <th class="bg-light">会員名</th>
                <th class="bg-light"></th>
                <th class="bg-light"></th>
              </tr>
            </thead>
            <tbody>
              <% @reviews.each do |review| %>
                <tr class="text-center">
                  <td class="align-middle text-center"><%= review.book.title %></td>
                  <td class="align-middle text-center"><%= review.customer.nickname %></td>
                  <td class="align-middle text-center"><%= link_to "詳細", admin_review_path(review), class: "btn btn-success btn-sm font-weight-bold" %></td>
                  <td class="align-middle text-center"><%= link_to "削除", admin_review_path(review), method: :delete, class: "btn btn-danger btn-sm font-weight-bold", data: { confirm: "レビューを削除してもよろしいですか？" } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @reviews %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<div class="container my-4 px-md-0">
  <div class="col-12 col-sm-5 col-md-4 col-lg-3 col-xl-2 px-1 ml-md-2">
    <h5 class="bg-light text-center font-weight-bold ml-md-5 mb-4 text-nowrap">レビュー詳細</h5>
  </div>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr class="bg-light text-center">
          <th></th>
          <th>タイトル</th>
          <th>著者</th>
          <th>レビュー投稿者</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr class="text-center">
          <td class="align-middle text-center"><%= image_tag(@review.book.small_image_url, class: "book-image") %></td>
          <td class="align-middle text-center"><%= @review.book.title %></td>
          <td class="align-middle text-center"><%= @review.book.author %></td>
          <td class="align-middle text-center"><%= @review.customer.nickname %></td>
          <td class="align-middle text-center"><%= link_to "削除", admin_review_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'col-9 btn btn-danger font-weight-bold'  %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= form_with model:@review, local: true do |f| %>
        <table class="table table-borderless">
          <!--星の表示-->
          <tr>
            <th style="font-size:18px;">星</th>
            <td>
              <div id="star_<%= @review.id %>"></div>
              <script>
              $(document).on('turbolinks:load', function() {
                let elem = document.querySelector('#star_<%= @review.id %>');
                if (elem == null) return;

                elem.innerHTML = "";
                let opt = {
                  starOn: "<%= asset_path('star-on.png') %>",
                  starOff: "<%= asset_path('star-off.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                  score: "<%= @review.star %>",
                  readOnly: true,
                };
                raty(elem, opt);
              });
              </script>
            </td>
          </tr>
          <!--感想の表示-->
          <tr>
            <th style="font-size:18px;">感想</th>
            <td style="font-size:16px;"><%= @review.impression %></td>
          </tr>
          <!--活かしたいことの表示-->
          <tr>
            <th class="text-nowrap" style="font-size:18px;">活かしたいこと</th>
            <td style="font-size:16px;"><%= @review.action%></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>