config/routes.rb
Rails.application.routes.draw do
  
  #共通
  root to:'public/homes#top'
  get 'about' => 'public/homes#about'

  #会員用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#following', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'customers/:id/check' => "customers#check", as: 'check'
    patch 'customers/:id/withdrawal' => "customers#withdrawal", as: 'withdrawal'

    resources :books
    get 'books/search', to: "books#search"
    
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    
    get 'tagsearches/search', to: 'tagsearches#search'
    
    get 'ranks' => 'ranks#rank', as: "rank"

  end

  #管理者用
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :destroy]
  end

  # ゲストログイン
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/book2.rb
class Book2 < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # バリデーション
  validates :nickname, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  # Active_Storage
  has_one_attached :profile_image

  # プロフィール画像
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ステータスが「退会済」になっている人がログインできないようにする
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end

  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end

  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end
  
  # 会員ステータスが「有効」の場合のフォロワー数
  def active_followers_count
    followers.where(is_deleted: false).count
  end

  # 会員ステータスが「有効」の場合のフォロー数
  def active_followings_count
    followings.where(is_deleted: false).count
  end

  # ゲストログイン関連
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.nickname = "ゲスト"
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/review.rb
class Review < ApplicationRecord
  
  # アソシエーション
  belongs_to :customer
  belongs_to :book
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # バリデーション
  validates :star, presence: true
  validates :category, presence: true
  validates :impression, presence: true
  validates :action, presence: true
  
  # いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  
  # ソート機能
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @reviews = Review.page(params[:page]).per(5)
  end

  def show
    @review = Review.find(params[:id])
  end
  
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = "レビューを削除しました。"
    redirect_to admin_reviews_path
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    admin_customers_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  add_flash_types :success, :info, :warning, :danger

  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "dark"
    when "error"
      "danger"
    when "danger"
      "danger"
    when "info"
      "info"
    when "success"
      "success"
    when "warning"
      "warning"
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" class="alert alert-danger p-0 mb-2">
    <ul class="mb-0">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message| %>
  <div class="alert alert-<%= bootstrap_alert(message[0]) %> alert-dismissible fade show">
    <% if message[1].is_a?(Array) %>
      <% message[1].each do |value| %>
        <span><%= value %><br></span>
      <% end %>
    <% else %>
      <span><%= message[1] %></span>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white d-flex align-items-center justify-content-center" style="height: 80px;">
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3 text-center" style="font-size:20px;">
        Page2Action
      </div>
      <div class="col-3 text-right">
        <% unless admin_signed_in? || customer_signed_in? %>
          管理者の方は<%= link_to "こちら", new_admin_session_path %>
        <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">
      <a class="navbar-brand p-1" href="/"><%= image_tag "logo.png", size: "70x70" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

            <!--カスタマーログイン時-->
            <% if customer_signed_in? %>
               <li class="nav-item m-1">
                 <%= link_to "マイページ", customer_path(current_customer), class: 'nav-link text-dark btn btn-outline-light', style: "width: 95px;" %>
               </li>
               <li class="nav-item m-1">
                 <%= link_to "読書家検索", customers_path, class: 'nav-link text-dark btn btn-outline-light', style: "width: 100px;" %>
               </li>
               <li class="nav-item m-1">
                 <%= link_to "みんなの投稿", reviews_path, class: 'nav-link text-dark btn btn-outline-light', style: "width: 115px;"  %>
               </li>
               <li class="nav-item m-1">
                 <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-light', style: "width: 100px;" %>
               </li>
               <!--書籍検索-->
               <li class="nav-item m-1">
                 <%= form_tag(new_book_path, method: :get, class: 'form-inline') do %>
                   <div class="row">
                     <div class="col pr-0 pt-1">
                       <%= text_field_tag :title, @title, class: 'form-control', placeholder:'タイトルを入力' %>
                     </div>
                     <div class="col pl-1 pt-1">
                       <button class="btn btn-primary" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                     </div>
                   </div>
                 <% end %>
               </li>

            <!--管理者ログイン時-->
            <% elsif admin_signed_in? %>
              <li class="nav-item m-1">
                <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark btn btn-outline-light' %>
              </li>
              <li class="nav-item m-1">
                <%= link_to "レビュー一覧", admin_reviews_path, class: 'nav-link text-dark btn btn-outline-light' %>
              </li>
              <li class="nav-item m-1">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-light' %>
              </li>

　　　　　　<!--ログアウト時-->
            <% else %>
              <li class="nav-item m-1">
                <%= link_to "About", about_path, class: 'nav-link text-dark btn btn-outline-light' %>
              </li>
              <li class="nav-item m-1">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark btn btn-outline-light' %>
              </li>
              <li class="nav-item m-1">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark btn btn-outline-light' %>
              </li>
            <% end %>
          </ul>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Page2Action</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5071dcf09a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <%= render "layouts/header" %>
    </div>
    <div class="main" style="background-color:#f9f7f3;">
      <%= render 'layouts/flash_message' %>
      <%= yield %>
    </div>
    <div class="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>